[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = ["cd backend && pip install --upgrade pip && pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build conclu√≠do'"]

[start]
cmd = "cd backend && uvicorn app:app --host 0.0.0.0 --port $PORT"
